apiVersion: apps/v1
kind: Deployment
metadata:
  name: athlete-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: athlete-db
  template:
    metadata:
      labels:
        app: athlete-db
    spec:
      containers:
        - name: postgres
          image: postgres:17
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: athlete_db
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-pvc
