resources:
  - configmap.yaml
  - secret.yaml
  - postgres-config.yaml
  - db-pvc.yaml
  - db-deployment.yaml
  - db-service.yaml
  - init-db-job.yaml
  - deployment.yaml
  - service.yaml
  - network-policy.yaml
