apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-servers-config
  labels:
    app.kubernetes.io/name: pgadmin
    app.kubernetes.io/instance: database-tools
    app.kubernetes.io/component: database-admin
    app.kubernetes.io/part-of: athlefi
    app.kubernetes.io/managed-by: kustomize
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "AthleFi Athlete Database",
          "Group": "AthleFi",
          "Host": "athlete-db",
          "Port": 5432,
          "MaintenanceDB": "athlete_db",
          "Username": "postgres",
          "SSLMode": "prefer",
          "SSLCert": "<STORAGE_DIR>/.postgresql/postgresql.crt",
          "SSLKey": "<STORAGE_DIR>/.postgresql/postgresql.key",
          "SSLCompression": 0,
          "Timeout": 10,
          "UseSSHTunnel": 0,
          "TunnelHost": "",
          "TunnelPort": "22",
          "TunnelUsername": "",
          "TunnelAuthentication": 0
        }
      }
    }
