apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pgadmin
  labels:
    app.kubernetes.io/name: pgadmin
    app.kubernetes.io/instance: database-tools
    app.kubernetes.io/component: database-admin
    app.kubernetes.io/part-of: athlefi
    app.kubernetes.io/managed-by: kustomize
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
    - host: pgadmin-dev.athlefi.internal.mx-central-1.sparkfly.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pgadmin
                port:
                  number: 80
  tls:
    - hosts:
        - pgadmin-dev.athlefi.internal.mx-central-1.sparkfly.cloud
