apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  labels:
    app.kubernetes.io/name: cloudflare-api-token
    app.kubernetes.io/instance: certificates
    app.kubernetes.io/component: dns-provider
    app.kubernetes.io/part-of: athlefi
    app.kubernetes.io/managed-by: kustomize
type: Opaque
stringData:
  # Replace with your actual Cloudflare API token
  api-token: "your-cloudflare-api-token-here"
