apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: athlefi-letsencrypt
  labels:
    app.kubernetes.io/name: athlefi-letsencrypt
    app.kubernetes.io/instance: certificates
    app.kubernetes.io/component: issuer
    app.kubernetes.io/part-of: athlefi
    app.kubernetes.io/managed-by: kustomize
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: kevin.olvera@dedsec.com.mx
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: athlefi-letsencrypt
    # Add challenge solvers
    solvers:
      - http01:
          ingress:
            class: traefik
      - dns01:
          # Use Cloudflare DNS challenge for wildcard certificates
          cloudflare:
            email: kevin.olvera@dedsec.com.mx
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
