apiVersion: v1
kind: Secret
metadata:
  name: athlete-db-secret
  labels:
    app.kubernetes.io/name: athlete-db
    app.kubernetes.io/instance: athlete-service
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: athlefi
    app.kubernetes.io/managed-by: kustomize
type: Opaque
stringData:
  DB_PASSWORD: postgres
