apiVersion: apps/v1
kind: Deployment
metadata:
  name: athlete-api
  labels:
    app.kubernetes.io/name: athlete-api
    app.kubernetes.io/instance: athlete-service
    app.kubernetes.io/version: v11
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: athlefi
    app.kubernetes.io/managed-by: kustomize
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: athlete-api
      app.kubernetes.io/instance: athlete-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: athlete-api
        app.kubernetes.io/instance: athlete-service
        app.kubernetes.io/version: v11
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: athlefi
        app.kubernetes.io/managed-by: kustomize
    spec:
      imagePullSecrets:
        - name: regcred
      imagePullPolicy: Always
      containers:
        - name: athlete-api
          image: registry.sparkfly.cloud/athlefi/athlete-api:v11
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: athlete-db-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: athlete-db-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: athlete-db-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: athlete-db-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: athlete-db-secret
                  key: DB_PASSWORD
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
