apiVersion: v1
kind: ConfigMap
metadata:
  name: athlete-db-postgres-config
  labels:
    app.kubernetes.io/name: athlete-db
    app.kubernetes.io/instance: athlete-service
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: athlefi
    app.kubernetes.io/managed-by: kustomize
data:
  postgresql.conf: |
    # Basic settings
    listen_addresses = '*'
    port = 5432
    max_connections = 100

    # Memory settings
    shared_buffers = 256MB
    effective_cache_size = 1GB

    # Logging
    log_statement = 'all'
    log_destination = 'stderr'
    logging_collector = on
    log_directory = 'log'
    log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'

    # Connection settings
    tcp_keepalives_idle = 600
    tcp_keepalives_interval = 30
    tcp_keepalives_count = 3

    # Performance settings
    random_page_cost = 1.1
    effective_io_concurrency = 200

    # Security settings for non-root execution
    unix_socket_directories = '/var/run/postgresql'
    unix_socket_permissions = 0777

  pg_hba.conf: |
    # TYPE  DATABASE        USER            ADDRESS                 METHOD
    local   all             all                                     trust
    host    all             all             127.0.0.1/32            trust
    host    all             all             ::1/128                 trust
    host    all             all             0.0.0.0/0               md5
