apiVersion: v1
kind: Service
metadata:
  name: athlete-db
  labels:
    app.kubernetes.io/name: athlete-db
    app.kubernetes.io/instance: athlete-service
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: athlefi
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    app.kubernetes.io/name: athlete-db
    app.kubernetes.io/instance: athlete-service
  ports:
    - port: 5432
      targetPort: 5432
      name: postgresql
      protocol: TCP
